### PR TITLE
feat: initial draft of the Dockerfile alternative

### PR DESCRIPTION
**Pull request by Daniel-Boll**
Remaining tasks

- [x] Configure a CI to release this into the [GitHub Docker Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry)
- [ ] Configure to do a `npm` release and [GitHub NPM Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)
  The goal is the following:
  ```bash
  npx @basementdevs/scylla-studio@latest
  ```
- [x] (optional) Try to make the Dockerfile image `alpine` to save some space. [@gvieira18]

---

## Running Scylla Studio via Docker

You can run Scylla Studio directly through Docker without setting up the entire environment. To do this, run the following one-liner:

```bash
docker run --rm --name scylla-studio --network="host" ghcr.io/basementdevs/scylla-studio:latest
```

### Persistent Volumes

If you'd like to keep the session data and logs between runs, you can use Docker volumes:

```bash
docker run --rm --name scylla-studio --network="host" \
  -v scylla-studio-data:/usr/app/data \
  ghcr.io/basementdevs/scylla-studio:latest
```

This will create a persistent volume named `scylla-studio-data` for the application's data.

To remove the volume later:

```bash
docker volume rm scylla-studio-data
```

### CODE REVIEW

**Comment by Daniel-Boll** [comment]
The build command I'm currently using is the following:

```bash
docker buildx build -t basementdevs/scylla-studio .
```

**Review by DanielHe4rt — APPROVED** [review]
LGTM!

**Comment by Daniel-Boll** [comment]
<h1 align="center"> Copilot Summary </h1>

This pull request includes significant updates to Docker support, dependency management, and code formatting. The most important changes include the addition of a Dockerfile, updates to the `compose.yml` for Docker Compose, improvements in the `README.md` for Docker usage instructions, and various code formatting and dependency adjustments.

### Docker Support:

* Added a new `Dockerfile` to build and run the application using a Debian-based Node.js image. This includes stages for dependencies, building, and production setup. (`Dockerfile`)
* Updated `compose.yml` to define services for `scylladb` and `scylla-studio`, including resource limits, ports, and network settings. (`compose.yml`)

### Documentation:

* Enhanced `README.md` with instructions on running Scylla Studio via Docker, including commands for persistent volumes. (`README.md`)

### Code Formatting and Dependency Management:

* Updated `next.config.mjs` to set the output to "standalone" for better Docker compatibility. (`next.config.mjs`)
* Moved `@types/better-sqlite3` from dependencies to devDependencies in `package.json` and updated `pnpm-lock.yaml` accordingly. (`package.json`, `pnpm-lock.yaml`) [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L30) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R52) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL65-L67) [[4]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR126-R128)
* Reformatted `tracing-dashboard-render.tsx` for better readability and consistency, including fixing import statements and improving state management. (`src/app/(main)/query-runner/_components/tracing-dashboard-render.tsx`) [[1]](diffhunk://#diff-682ae8123ec2949dd9bcb6216d6d990a63cd12a28f70a7ac12b62a9daa0974c0L1-R196) [[2]](diffhunk://#diff-682ae8123ec2949dd9bcb6216d6d990a63cd12a28f70a7ac12b62a9daa0974c0L311-R362) [[3]](diffhunk://#diff-682ae8123ec2949dd9bcb6216d6d990a63cd12a28f70a7ac12b62a9daa0974c0L338-R410) [[4]](diffhunk://#diff-682ae8123ec2949dd9bcb6216d6d990a63cd12a28f70a7ac12b62a9daa0974c0L354-R433) [[5]](diffhunk://#diff-682ae8123ec2949dd9bcb6216d6d990a63cd12a28f70a7ac12b62a9daa0974c0L371-R465)

### Component Refactoring:

* Refactored `Label` component to use Radix UI and class-variance-authority for styling. (`src/components/ui/label.tsx`)

### Database Path Adjustment:

* Modified the database path in `connections.ts` to use a relative path for better compatibility with Docker. (`src/lib/internal-db/connections.ts`) [[1]](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL3-R3) [[2]](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL23-R28) [[3]](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL45-R45)

**Comment by Daniel-Boll** [comment]
I took this base docker image from elsewhere, but I'm not sure why the new user though.

About the error, that's odd. Can you try to add `pnpm rebuild` after the installation?

**Comment by Daniel-Boll** [comment]
I manage to get a working image with less than 200 MiB with `cgr.dev/chainguard/node:latest-dev` and `cgr.dev/chainguard/node:latest-dev` I think that's already pretty good.

**Comment by YvanDaSilva** [comment]
> I manage to get a working image with less than 200 MiB with `cgr.dev/chainguard/node:latest-dev` and `cgr.dev/chainguard/node:latest-dev` I think that's already pretty good.

Was going to recommend that before leaving stream yesterday in case distroless was not a success.

Glad you got it work :) Congrats.

<200mb is fine for a nodejs image. Try: https://github.com/wagoodman/dive to explore your image, you will see that nodejs alone is 110+MiB

**Comment by Daniel-Boll** [comment]
> I just tried your image, it still spews the same error.

Is there any chance of that being a cache problem? I'll try to prune what I have here and test again to see if I can reproduce it. It would be a good idea if @gvieira18 or @DanielHe4rt could test it too.

**Comment by diegoreis42** [comment]
I tested on my local machine and it worked fine. I built and ran manually with `docker buildx build -t basementdevs/scylla-studio .`

**Comment by gvieira18** [comment]
Tested locally and worked as expected.

```sh
docker build \
  --label "org.opencontainers.image.source=https://github.com/basementdevs/scylla-studio" \
  --label "org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --tag "basementdevs/scylla-studio:main" \
  --tag "basementdevs/scylla-studio:develop" \
  --progress=plain \
  --file Dockerfile \
  .
```

image

**Comment by YvanDaSilva** [comment]
Very likely something is wrong on my machine (macos aarch64). This means distroless also worked 🙈 lol.
Merge on :D

**Comment by Daniel-Boll** [comment]
> This means distroless also worked 🙈 lol

I couldn't make the distroless one work on my machine, that's why I tried to move to this one. Hopefully it will work on mac eventually, lol. :pray:

**Pull request merged**
